[master]
# Jenkins/Terraform generated
# Replace placeholders if you generate inventory manually
# Example: master_ip ansible_host=1.2.3.4

[workers]
# worker1 ansible_host=...
# worker2 ansible_host=...

